!function(){function e(i,n,t){var r,s,l=e.resolve(i)
if(null==l)throw t=t||i,n=n||"root",r=Error('Failed to require "'+t+'" from "'+n+'"'),r.path=t,r.parent=n,r.require=!0,r
return s=e.modules[l],s.exports||(s.exports={},s.client=s.component=!0,s.call(this,s.exports,e.relative(l),s)),s.exports}e.modules={},e.aliases={},e.resolve=function(i){var n,t
for("/"===i.charAt(0)&&(i=i.slice(1)),n=[i,i+".js",i+".json",i+"/index.js",i+"/index.json"],t=0;t<n.length;t++){if(i=n[t],e.modules.hasOwnProperty(i))return i
if(e.aliases.hasOwnProperty(i))return e.aliases[i]}},e.normalize=function(e,i){var n,t=[]
if("."!=i.charAt(0))return i
for(e=e.split("/"),i=i.split("/"),n=0;n<i.length;++n)".."==i[n]?e.pop():"."!=i[n]&&""!=i[n]&&t.push(i[n])
return e.concat(t).join("/")},e.register=function(i,n){e.modules[i]=n},e.alias=function(i,n){if(!e.modules.hasOwnProperty(i))throw Error('Failed to alias "'+i+'", it does not exist')
e.aliases[n]=i},e.relative=function(i){function n(e,i){for(var n=e.length;n--;)if(e[n]===i)return n
return-1}function t(n){var r=t.resolve(n)
return e(r,i,n)}var r=e.normalize(i,"..")
return t.resolve=function(t){var s,l,o=t.charAt(0)
return"/"==o?t.slice(1):"."==o?e.normalize(r,t):(s=i.split("/"),l=n(s,"deps")+1,l||(l=0),t=s.slice(0,l+1).join("/")+"/deps/"+t)},t.exists=function(i){return e.modules.hasOwnProperty(t.resolve(i))},t},e.register("readint/bin/readint.js",function(e,i,n){n.exports=i("../lib/readint.js")}),e.register("readint/lib/readint.js",function(e,i,n){function t(e,n){return isNaN(global=parseInt(e))?(void 0===n&&(n="en"),n=i("../locales/"+n),(tokens=s(e,n)).length>0?r(tokens,n):-1):global}function r(e,i){var n,t,s,l,o
if(0==e.length)return-1
if(1==e.length)return e[0].value
for(s=-1,l=0,o=-1;l<e.length;++l)e[l].level>o&&(o=e[l].level,s=l)
return-1==(n=r(e.slice(0,s)))&&(n=1),-1==(t=r(e.slice(s+1,e.length)))&&(t=0),void 0!==i.LTRlevels&&-1!=i.LTRlevels.indexOf(s)?n+e[s].value+t:n*e[s].value+t}function s(e,i){var n,t,r=e.split(i.splitter),s=l(i.values),o=[]
for(void 0===i.filters&&(i.filters=[]),n=0;void 0!==r[n];++n)if(0!=(r[n]=r[n].toLowerCase()).length){for(t=0;t<i.filters.length;++t)r[n]=r[n].replace(i.filters[t][0],i.filters[t][1])
for(t=0;;++t){if(t>=s.length){r.splice(n--,1)
break}if(r[n]==s[t].string){o.push(s[t])
break}}}else r.splice(n--,1)
return o}function l(e){var i,n,t=[]
for(i=0;i<e.length;++i)for(n in e[i])t.push({string:n,value:e[i][n],level:i})
return t}n.exports=t}),e.register("readint/locales/en.js",function(e,i,n){n.exports={splitter:/\s|\sand/,filters:[[/ies?$/,"y"],[/s$/,""]],values:[{zero:0,one:1,two:2,three:3,four:4,five:5,six:6,seven:7,eight:8,nine:9,eleven:11,twelve:12,thirteen:13,fourteen:14,fifteen:15,sixteen:16,seventeen:17,eighteen:18,nineteen:19},{ten:10,twenty:20,thirty:30,forty:40,fifty:50,sixty:60,seventy:70,eighty:80,ninety:90},{hundred:100},{thousand:1e3},{million:1e6},{billion:1e9},{trillion:1e12}]}}),e.register("readint/locales/es.js",function(e,i,n){n.exports={splitter:/\s|\sy/,filters:[[/á/,"a"],[/é/,"e"],[/ú/,"u"],[/ó/,"o"],[/ñ/,"n"],[/í/,"i"]],values:[{zero:0,uno:1,dos:2,tres:3,cuatro:4,cinco:5,seis:6,siete:7,ocho:8,nueve:9,once:11,doze:12,trece:13,catorce:14,quince:15,diecisies:16,diecisiete:17,dieciocho:18,diecinueve:19,veintiuno:21,veintidos:22,veintitres:23,veinticuatro:24,veinticinco:25,veintiseis:26,veintisiete:27,veintiocho:28,veintinueve:29},{diez:10,veinte:20,treinta:30,cuarenta:40,cicuenta:50,sensta:60,setenta:70,ochenta:80,noventa:90},{cien:100,ciento:100,dosciento:200,trescientos:300,cuatrocientos:400,quinientos:500,seiscientos:600,setecientos:700,ochocientos:800,novecientos:900},{mil:1e3},{millon:1e6,millone:1e6},{billon:1e9,billone:1e9},{trillon:1e12,trillone:1e12}]}}),e.register("readint/locales/fr.js",function(e,i,n){n.exports={splitter:/\s|et|-(?=[^vingt|dix])/,filters:[[/s$/,""],[/[àâ]/,"a"],[/[êéèë]/,"e"],[/[ùûûü]/,"u"],[/ô/,"o"],[/ç/,"c"],[/[îï]/,"i"]],values:[{zero:0,un:1,deux:2,troi:3,quatre:4,cinq:5,six:6,sept:7,huit:8,neuf:9,onze:11,douze:12,treize:13,quatorze:14,quinze:15,seize:16},{dix:10,vingt:20,trente:30,quarente:40,cinquante:50,soixante:60,"soixante-dix":70,"quatre-vingt":80,"quatre-vingt-dix":90},{cent:100},{mille:1e3},{million:1e6},{milliard:1e9},{billion:1e12}]}}),e.register("readint/locales/de.js",function(e,i,n){n.exports={splitter:/-|(hundert|tausend|million|milliard|billion)|und(?!ert)|\s/,filters:[[/ä/,"a"],[/ö/,"o"],[/ü/,"u"],[/ß/,"ss"],[/[es][ns]?$/,""]],LTRlevels:[1],values:[{"null":0,ein:1,zwei:2,drei:3,vier:4,fuenf:5,sech:6,sieben:7,acht:8,neun:9,elf:11,zwoelf:12,dreizehn:13,vierzehn:14,fuenfzehn:15,sechzehn:16,siebzehn:17,achtzehn:18,neunzehn:19},{zehn:10,zwanzig:20,dreissig:30,vierzig:40,fuenfzig:50,sechzig:60,siebzig:70,achtzig:80,neunzig:90},{hundert:100},{tausend:1e3},{million:1e6},{milliard:1e9},{billion:1e12}]}}),e.alias("readint/bin/readint.js","readint/index.js"),"object"==typeof exports?module.exports=e("readint"):"function"==typeof define&&define.amd?define(function(){return e("readint")}):this.readint=e("readint")}()